// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeatherRequest struct {
	CityCode             string   `protobuf:"bytes,1,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherRequest) Reset()         { *m = WeatherRequest{} }
func (m *WeatherRequest) String() string { return proto.CompactTextString(m) }
func (*WeatherRequest) ProtoMessage()    {}
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{0}
}

func (m *WeatherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherRequest.Unmarshal(m, b)
}
func (m *WeatherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherRequest.Marshal(b, m, deterministic)
}
func (m *WeatherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherRequest.Merge(m, src)
}
func (m *WeatherRequest) XXX_Size() int {
	return xxx_messageInfo_WeatherRequest.Size(m)
}
func (m *WeatherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherRequest proto.InternalMessageInfo

func (m *WeatherRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

type WeatherResponse struct {
	Temperature          float32  `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherResponse) Reset()         { *m = WeatherResponse{} }
func (m *WeatherResponse) String() string { return proto.CompactTextString(m) }
func (*WeatherResponse) ProtoMessage()    {}
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{1}
}

func (m *WeatherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherResponse.Unmarshal(m, b)
}
func (m *WeatherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherResponse.Marshal(b, m, deterministic)
}
func (m *WeatherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherResponse.Merge(m, src)
}
func (m *WeatherResponse) XXX_Size() int {
	return xxx_messageInfo_WeatherResponse.Size(m)
}
func (m *WeatherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherResponse proto.InternalMessageInfo

func (m *WeatherResponse) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type ListCitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCitiesRequest) Reset()         { *m = ListCitiesRequest{} }
func (m *ListCitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCitiesRequest) ProtoMessage()    {}
func (*ListCitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{2}
}

func (m *ListCitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCitiesRequest.Unmarshal(m, b)
}
func (m *ListCitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListCitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCitiesRequest.Merge(m, src)
}
func (m *ListCitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCitiesRequest.Size(m)
}
func (m *ListCitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCitiesRequest proto.InternalMessageInfo

type ListCitiesResponse struct {
	Items                []*CityEntry `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListCitiesResponse) Reset()         { *m = ListCitiesResponse{} }
func (m *ListCitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCitiesResponse) ProtoMessage()    {}
func (*ListCitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{3}
}

func (m *ListCitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCitiesResponse.Unmarshal(m, b)
}
func (m *ListCitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCitiesResponse.Marshal(b, m, deterministic)
}
func (m *ListCitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCitiesResponse.Merge(m, src)
}
func (m *ListCitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCitiesResponse.Size(m)
}
func (m *ListCitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCitiesResponse proto.InternalMessageInfo

func (m *ListCitiesResponse) GetItems() []*CityEntry {
	if m != nil {
		return m.Items
	}
	return nil
}

type CityEntry struct {
	CityCode             string   `protobuf:"bytes,1,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	CityName             string   `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityEntry) Reset()         { *m = CityEntry{} }
func (m *CityEntry) String() string { return proto.CompactTextString(m) }
func (*CityEntry) ProtoMessage()    {}
func (*CityEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{4}
}

func (m *CityEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityEntry.Unmarshal(m, b)
}
func (m *CityEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityEntry.Marshal(b, m, deterministic)
}
func (m *CityEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityEntry.Merge(m, src)
}
func (m *CityEntry) XXX_Size() int {
	return xxx_messageInfo_CityEntry.Size(m)
}
func (m *CityEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CityEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CityEntry proto.InternalMessageInfo

func (m *CityEntry) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *CityEntry) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func init() {
	proto.RegisterType((*WeatherRequest)(nil), "WeatherRequest")
	proto.RegisterType((*WeatherResponse)(nil), "WeatherResponse")
	proto.RegisterType((*ListCitiesRequest)(nil), "ListCitiesRequest")
	proto.RegisterType((*ListCitiesResponse)(nil), "ListCitiesResponse")
	proto.RegisterType((*CityEntry)(nil), "CityEntry")
}

func init() { proto.RegisterFile("weather.proto", fileDescriptor_231dcd72b885f4be) }

var fileDescriptor_231dcd72b885f4be = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x45, 0xb1, 0x53, 0xb5, 0xba, 0xbd, 0x84, 0x7a, 0x89, 0xf1, 0xd2, 0x8b, 0x1b,
	0x69, 0xd0, 0x07, 0x30, 0x94, 0x5e, 0x44, 0x34, 0x1e, 0x04, 0x2f, 0xb2, 0x49, 0x86, 0x76, 0x0f,
	0x9b, 0x8d, 0xbb, 0xb3, 0x96, 0x80, 0x0f, 0x2f, 0x9a, 0xb2, 0xad, 0x16, 0xbc, 0x7e, 0xff, 0xee,
	0xcc, 0x7c, 0x33, 0x70, 0xbc, 0x42, 0x41, 0x4b, 0x34, 0xbc, 0x31, 0x9a, 0x74, 0x7c, 0x05, 0x27,
	0x2f, 0x1d, 0xc8, 0xf1, 0xdd, 0xa1, 0x25, 0x76, 0x0e, 0xfd, 0x52, 0x52, 0xfb, 0x56, 0xea, 0x0a,
	0xc3, 0x20, 0x0a, 0x26, 0xfd, 0xfc, 0xf0, 0x1b, 0x64, 0xba, 0xc2, 0x38, 0x85, 0xa1, 0x7f, 0x6e,
	0x1b, 0x5d, 0x5b, 0x64, 0x11, 0x0c, 0x08, 0x55, 0x83, 0x46, 0x90, 0x33, 0xdd, 0x8f, 0x5e, 0xbe,
	0x8d, 0xe2, 0x11, 0x9c, 0xdd, 0x4b, 0x4b, 0x99, 0x24, 0x89, 0x76, 0xdd, 0x26, 0xbe, 0x05, 0xb6,
	0x0d, 0x7d, 0xb1, 0x7d, 0x49, 0xa8, 0x6c, 0x18, 0x44, 0x7b, 0x93, 0xc1, 0x14, 0x78, 0x26, 0xa9,
	0x9d, 0xd5, 0x64, 0xda, 0xbc, 0x0b, 0xe2, 0x19, 0xf4, 0x3d, 0xfb, 0x77, 0x56, 0x1f, 0xd6, 0x42,
	0x61, 0xd8, 0xdb, 0x84, 0x0f, 0x42, 0xe1, 0xf4, 0xd3, 0x7b, 0x3f, 0xa3, 0xf9, 0x90, 0x25, 0xb2,
	0x14, 0x8e, 0x9e, 0x1c, 0x9a, 0x76, 0x8d, 0xd9, 0x90, 0xff, 0x5e, 0xcc, 0xf8, 0x94, 0xff, 0x51,
	0xbf, 0x0e, 0xd8, 0x0d, 0xc0, 0xc6, 0x82, 0x31, 0xbe, 0xe3, 0x39, 0x1e, 0xf1, 0x5d, 0xcd, 0xbb,
	0xcb, 0xd7, 0x8b, 0x85, 0xa4, 0xa5, 0x2b, 0x78, 0xa9, 0x55, 0x32, 0x77, 0xa6, 0x10, 0xb5, 0x5e,
	0xcd, 0x45, 0x25, 0x54, 0xb2, 0xc8, 0x1f, 0xb3, 0x44, 0x34, 0xb2, 0x38, 0xf8, 0xb9, 0x50, 0xfa,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x66, 0x69, 0xfd, 0xb2, 0x01, 0x00, 0x00,
}
